env:
  JULIA_VERSION: "1.9.3"

steps:

  - label: ":sunrise: initialize julia"
    command: 
      - "module load julia"
      - "echo $JULIA_VERSION"
      - "julia --project=docs/ -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(); Pkg.status()'"
   
  - wait 

  - label: "run tests"
    command:
      - "srun --mem=8G --time=1:00:00 --output=log_%j.log jobscript.sh"

  - wait

